#include <stdio.h>
#include <string.h>

// Generated by Claude
void encrypt(unsigned char *data, int length) {
    for (int i = 0; i < length; i++) {
        unsigned char c = data[i];
        c = (c << 2) | (c >> 6);  // Rotate left by 2
        c ^= 0xAA;                // XOR with pattern
        c += i % 5;               // Position-dependent addition
        data[i] = c;
    }
}

unsigned char ciphertext[] = {139, 48, 109, 110, 83, 42, 148, 65, 122, 46, 207, 64, 49, 102, 50, 46, 47, 132, 133, 211, 23, 128, 44, 42, 31, 15, 32, 37, 66, 63, 42, 48, 44, 34, 27, 127, 20, 125, 50, 19, 19, 27, 44, 50, 103, 63, 43, 81, 26, 131, 42, 104, 49, 126, 19, 103, 52, 17, 66, 63, 86, 131, 177, 106, 46, 79, 24, 129, 45, 107, 123, 48, 21, 62, 46, 47, 124, 44, 126, 15, 63, 43, 125, 26, 111, 130, 208, 25, 130, 46, 47, 28, 101, 66, 51, 59, 80, 44, 122, 51, 19, 20, 49, 45, 63, 23, 43, 125, 14, 19, 103, 131, 153, 22, 67, 42, 32, 25, 102, 67, 42, 124, 17, 34, 67, 130, 0};

int main(){
    char buf[0x100];
    int len = strlen(ciphertext);
    for(int i=0;i<len; i++){
        buf[i] = getchar();
    }
    encrypt(buf, len);
    if(strcmp(buf, ciphertext)){
        puts("Wrong");
    } else {
        puts("Right!");
    }
};