// Contents generated by claude

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// RC4 State Structure
typedef struct {
    unsigned char S[256];
    int i, j;
} RC4_state;

// Initialize RC4 state with key
void rc4_init(RC4_state *state, const unsigned char *key, int key_length) {
    // Initialize state array
    for (int i = 0; i < 256; i++) {
        state->S[i] = i;
    }

    // Key-scheduling algorithm (KSA)
    int j = 0;
    for (int i = 0; i < 256; i++) {
        j = (j + state->S[i] + key[i % key_length]) % 256;
        
        // Swap elements
        unsigned char temp = state->S[i];
        state->S[i] = state->S[j];
        state->S[j] = temp;
    }

    // Reset index values
    state->i = 0;
    state->j = 0;
}

// Generate pseudo-random byte (Pseudo-random generation algorithm - PRGA)
unsigned char rc4_generate_byte(RC4_state *state) {
    state->i = (state->i + 1) % 256;
    state->j = (state->j + state->S[state->i]) % 256;

    // Swap elements
    unsigned char temp = state->S[state->i];
    state->S[state->i] = state->S[state->j];
    state->S[state->j] = temp;

    // Return pseudo-random byte
    int k = (state->S[state->i] + state->S[state->j]) % 256;
    return state->S[k];
}

// Encrypt or decrypt data (RC4 is symmetric)
void rc4_process(RC4_state *state, 
                 const unsigned char *input, 
                 unsigned char *output, 
                 int length) {
    for (int n = 0; n < length; n++) {
        // XOR input byte with generated pseudo-random byte
        output[n] = input[n] ^ rc4_generate_byte(state);
    }
}

// Utility function to print byte array
void print_bytes(const unsigned char *data, int length) {
    for (int i = 0; i < length; i++) {
        printf("%02x ", data[i]);
    }
    printf("\n");
}

int main() {
    // Example usage
    const unsigned char key[] = "SecretKey123";
    const char* plaintext = "Hello, RC4 Encryption!";
    
    // Allocate buffers
    int text_length = strlen(plaintext);
    unsigned char *encrypted = malloc(text_length);
    unsigned char *decrypted = malloc(text_length);

    // Initialize RC4 state
    RC4_state state;
    rc4_init(&state, key, strlen(key));

    // Encrypt
    printf("Original:  %s\n", plaintext);
    printf("Original Bytes: ");
    print_bytes((unsigned char*)plaintext, text_length);
    
    rc4_process(&state, (unsigned char*)plaintext, encrypted, text_length);
    printf("Encrypted Bytes: ");
    print_bytes(encrypted, text_length);

    // Reset state for decryption
    rc4_init(&state, key, strlen(key));

    // Decrypt
    rc4_process(&state, encrypted, decrypted, text_length);
    decrypted[text_length] = '\0';  // Null-terminate
    printf("Decrypted: %s\n", decrypted);

    // Free memory
    free(encrypted);
    free(decrypted);

    return 0;
}